
import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import { Providers } from "@/providers/Providers";
import "./globals.css";
import { ClientProvider } from "@/providers/ClientProvider";
import { CurrentUserProvider } from "@/providers/CurrentUserProvide";

const inter = Inter({
  variable: "--font-inter",
||||||| 8f900d3
import { Inter } from "next/font/google";
import { Providers } from "@/providers/Providers";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
=======
>>>>>>> 9f73cfe891e3a815888bec3b0149147c1ad32420
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Fusion Fit..",
  description: "Stay health and good looking with FusionFit",
||||||| 8f900d3
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Fusion Gym",
  description: "Your premium fitness destination",
>>>>>>> 9f73cfe891e3a815888bec3b0149147c1ad32420
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
    return (
      <html lang="en">
        <body className={inter.variable}>
          <Providers>
            <ClientProvider>
              <CurrentUserProvider>
            {children}
            </CurrentUserProvider>
            </ClientProvider>
            </Providers>
        </body>
      </html>
    );
  }
||||||| 8f900d3
    return (
      <html lang="en">
        <body className={inter.variable}>
          <Providers>{children}</Providers>
        </body>
      </html>
    );
  }
=======

>>>>>>> 9f73cfe891e3a815888bec3b0149147c1ad32420
